minor grammatical fixes for clarity
rlespinasse/github-slug-action pull request #72
Opened 2021-08-02 18:52 UTC by jbcpollak

2021-08-02 19:08 UTC, rlespinasse requested changes
Thanks for your grammar review 👍 
To match the title change and make the link work, can you add the proposed suggestion?

2021-08-02 19:08 UTC, rlespinasse commented on README.md
> +    - [One of environement variables doesn't work as intended](#one-of-environement-variable-dont-work-as-intended)
```suggestion
    - [One of environement variables doesn't work as intended](#one-of-environement-variables-doesnt-work-as-intended)
```

2021-08-02 20:38 UTC, jbcpollak commented
thanks for catching that - while updating I noticed two more small problems and fixed those too.

2021-08-04 21:07 UTC, rlespinasse approved these changes

2021-08-04 21:07 UTC, merged