feat: add GITHUB_REF_NAME env var
rlespinasse/github-slug-action pull request #73
Opened 2021-08-25 19:24 UTC by Ameausoone

Resolves #71

2021-08-25 20:39 UTC, rlespinasse reviewed
Can you add some documentation on the README?

2021-08-25 20:39 UTC, rlespinasse commented on src/main.ts
> +  core.info(`branchName : ${branchName}`)
```suggestion
  if (isPullRequest) {
    branchName = process.env.GITHUB_HEAD_REF
  } else if (process.env.GITHUB_REF) {
    branchName = process.env.GITHUB_REF
  }
  core.info(`branchName : ${branchName}`)
```

2021-08-25 20:40 UTC, rlespinasse commented
@Ameausoone Can you also cleanup the commit messages?

2021-08-27 08:51 UTC, rlespinasse commented on src/main.ts
> +  core.exportVariable('GITHUB_YOLO', 'yolo')
YOLO 😱

2021-08-27 08:51 UTC, rlespinasse commented on src/main.ts
> +    core.info(`branchName : ${branchName}`)
remove this line. the branchName is printed later on

2021-08-31 17:35 UTC, rlespinasse commented
@Ameausoone can you review my additional changes to this PR?

2021-08-31 17:38 UTC, rlespinasse approved these changes

2021-09-05 05:11 UTC, rlespinasse commented
Since **GITHUB_REF** can also contain a tag name, I think we have two choices

1. Use **REF** (instead of `BRANCH`) like `GITHUB_REF_NAME` (or `GITHUB_REF_LABEL`)
2. Have two variables `GITHUB_BRANCH_NAME`, and `GITHUB_TAG_NAME` set when appropriate.

@Ameausoone any thoughts on that matter?

2021-09-10 10:51 UTC, rlespinasse requested changes

2021-09-10 10:51 UTC, rlespinasse commented on src/main.ts
> +    core.exportVariable(GITHUB_BRANCH_NAME, branchName)
```suggestion
    core.exportVariable(GITHUB_BRANCH_NAME, removeRef(branchName))
```

2021-09-12 19:07 UTC, Ameausoone commented on src/main.ts
> +    core.exportVariable(GITHUB_BRANCH_NAME, branchName)
👍

2021-09-12 19:40 UTC, Ameausoone commented
> Since **GITHUB_REF** can also contain a tag name, I think we have two choices
> 
> 1. Use **REF** (instead of `BRANCH`) like `GITHUB_REF_NAME` (or `GITHUB_REF_LABEL`)
> 2. Use two variables `GITHUB_BRANCH_NAME`, and `GITHUB_TAG_NAME` (set when appropriate).
> 
> @Ameausoone any thoughts on that matter?

Good idea, I vote for the 1st solution

2021-09-13 07:47 UTC, rlespinasse commented on .github/workflows/release-dryrun.yml
> +              "${{ env.GITHUB_BRANCH_NAME }}"
```suggestion
              "${{ env.GITHUB_REF_NAME }}"
```

2021-09-13 07:47 UTC, rlespinasse commented on README.md
> +- `GITHUB_BRANCH_NAME` will contains the branch name
```suggestion
- `GITHUB_REF_NAME` will contains the reference name (branch or tag)
```

2021-09-15 14:59 UTC, rlespinasse approved these changes

2021-09-15 15:00 UTC, merged